# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
mod_id = elysium_api
mod_name = Elysium-API
mod_license = LGPL-2.1
mod_version = 2.0.2
mod_group_id = net.jadenxgamer.elysium_api
mod_authors = ThatJadenXgamer
mod_description = Elysium is a library mod full of various Java and Data-Driven utilities to help both Mod Developers and Modpack Creators.

# Minecraft properties
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]

# Parchment properties
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

# NeoForge properties
neoforge_version = 21.1.230
loader_version_range=[1,)

# Dependencies
pal_version = 1.0.14+mc.1.21.1
player_anim_version = 2.0.0-alpha1+1.21
jei_version=19.27.0.340