modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#displayURL=""
logoFile = "elysium_api.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[modproperties.${mod_id}]
mixinConfig="template.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"