plugins {
    id 'asphodel-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = project.property('neoforge_1_21_1').toString()

    parchment {
        minecraftVersion = project.property('parchment_mc_1_21_1').toString()
        mappingsVersion = project.property('parchment_ver_1_21_1').toString()
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', project.mod_id.toString())
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }